"""migrate to v2

Revision ID: 1fb048660b06
Revises: dc4d3de373f5
Create Date: 2024-03-25 23:43:08.779509

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1fb048660b06"
down_revision = "dc4d3de373f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("chat", "image_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user",
        "last_online",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "last_online",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column("chat", "image_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("chat", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
