"""Added author_id, is_read, type to Message; added type to Chat

Revision ID: 78329aabe78e
Revises: ef455dc10884
Create Date: 2022-12-04 11:12:20.954895

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78329aabe78e'
down_revision = 'ef455dc10884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chat_type_enum = postgresql.ENUM('SAVED_MESSAGES', 'DIALOGUE', 'GROUP', name='chat_type')
    chat_type_enum.create(op.get_bind())
    op.add_column('chat', sa.Column('type', chat_type_enum, nullable=False))
    op.alter_column('chat', 'name', existing_type=sa.VARCHAR(), nullable=True)
    op.add_column('message', sa.Column('author_id', sa.Integer(), nullable=False))
    message_type_enum = postgresql.ENUM('TEXT', 'VOICE', 'FILE', name='message_type')
    message_type_enum.create(op.get_bind())
    op.add_column('message', sa.Column('type', message_type_enum, nullable=False))
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('message', 'content', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('message', 'is_edited', existing_type=sa.BOOLEAN(), nullable=False)
    op.create_foreign_key('message_author_id_fkey', 'message', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_author_id_fkey', 'message', type_='foreignkey')
    op.alter_column('message', 'is_edited', existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column('message', 'content', existing_type=sa.TEXT(), nullable=True)
    op.drop_column('message', 'is_read')
    op.drop_column('message', 'type')
    op.execute('DROP TYPE message_type;')
    op.drop_column('message', 'author_id')
    op.alter_column('chat', 'name', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column('chat', 'type')
    op.execute('DROP TYPE chat_type;')
    # ### end Alembic commands ###
