"""ondelete=CASCADE added to Message.chat_id

Revision ID: 7fcef6a19bf6
Revises: 33a9590c62bc
Create Date: 2024-06-02 14:34:40.553699

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7fcef6a19bf6"
down_revision = "33a9590c62bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("message_chat_id_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None,
        "message",
        "chat",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_chat_id_fkey",
        "message",
        "chat",
        ["chat_id"],
        ["id"],
    )
    # ### end Alembic commands ###
