"""server_default=now(); added CASCADE to ChatParticipant

Revision ID: dc4d3de373f5
Revises: 78329aabe78e
Create Date: 2022-12-06 15:49:45.528203

"""

from alembic import op
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = "dc4d3de373f5"
down_revision = "78329aabe78e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chat_participant_chat_id_fkey",
        "chat_participant",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_participant_participant_id_fkey",
        "chat_participant",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "chat_participant_chat_id_fkey",
        "chat_participant",
        "chat",
        ["chat_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_participant_participant_id_fkey",
        "chat_participant",
        "user",
        ["participant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("chat", "created_at", nullable=False, server_default=func.now())
    op.alter_column("message", "created_at", nullable=False, server_default=func.now())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chat_participant_chat_id_fkey",
        "chat_participant",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_participant_participant_id_fkey",
        "chat_participant",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "chat_participant_participant_id_fkey",
        "chat_participant",
        "user",
        ["participant_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_participant_chat_id_fkey",
        "chat_participant",
        "chat",
        ["chat_id"],
        ["id"],
    )
    op.alter_column("chat", "created_at", nullable=True, server_default=None)
    op.alter_column("message", "created_at", nullable=True, server_default=None)
    # ### end Alembic commands ###
