"""token model

Revision ID: ef455dc10884
Revises: 130215b2f81a
Create Date: 2022-11-20 20:00:04.861415

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef455dc10884"
down_revision = "130215b2f81a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ACCESS", "REFRESH", name="token_type"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "user_id", name="unique_token"),
    )
    op.create_index(op.f("ix_token_token"), "token", ["token"], unique=False)
    op.add_column("chat", sa.Column("image_url", sa.String(), nullable=True))
    op.drop_column("chat", "logo_url")
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.add_column(
        "chat",
        sa.Column("logo_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("chat", "image_url")
    op.drop_index(op.f("ix_token_token"), table_name="token")
    op.drop_table("token")
    # ### end Alembic commands ###
