FROM python:3.10.6-slim-bullseye as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install pipenv and compilation dependencies
RUN pip install pipenv && \
    apt-get update && \
    apt-get install -y --no-install-recommends gcc

# install python dependencies in /.venv
COPY backend/Pipfile .
COPY backend/Pipfile.lock .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install


FROM builder

WORKDIR /app

# use virtual env from builder stage
ENV PATH "/.venv/bin:$PATH"

# create and switch to a new user
RUN groupadd --system app && useradd --no-create-home --system -g app app
USER app
