FROM node:18.11.0-bullseye-slim as builder

WORKDIR /app

COPY etc/docker/frontend/entrypoint.frontend.dev.sh /etc

RUN chmod +x /etc/entrypoint.frontend.dev.sh

ENTRYPOINT ["/etc/entrypoint.frontend.dev.sh"]
