FROM node:18.11.0-bullseye-slim

WORKDIR /app

COPY etc/docker/frontend/entrypoint.frontend.dev.sh /etc

RUN chmod +x /etc/entrypoint.frontend.dev.sh && \
    yarn global add @quasar/cli

ENTRYPOINT ["/etc/entrypoint.frontend.dev.sh"]
